//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Furnitures
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealSet
    {
        public int Id { get; set; }
        public Nullable<int> IdClient { get; set; }
        public Nullable<int> IdAgent { get; set; }
        public Nullable<int> IdProduct { get; set; }
    
        public virtual AgentSet AgentSet { get; set; }
        public virtual ClientsSet ClientsSet { get; set; }
        public virtual ProductSet ProductSet { get; set; }
    }
}
